/* ============================================
   HR/HCM System — Sample Data
   ============================================ */
(function() {
window.HRData = {
  // ==========================================
  // EMPLOYEES
  // ==========================================
  employees: [
    {
      id: '1001',
      nameAr: 'أحمد بن عبدالله الحربي',
      nameEn: 'Ahmed Abdullah Al-Harbi',
      nationalId: '1098765432',
      nationality: { ar: 'سعودي', en: 'Saudi' },
      isSaudi: true,
      mobile: '+966 55 123 4567',
      email: 'ahmed.harbi@company.sa',
      nationalAddress: { ar: 'الرياض - حي العليا - شارع الملك فهد', en: 'Riyadh - Al-Olaya District - King Fahd Road' },
      qualification: { ar: 'بكالوريوس إدارة أعمال', en: 'Bachelor of Business Administration' },
      department: { ar: 'قطاع التقنية', en: 'Technology Sector' },
      sector: { ar: 'قطاع التقنية', en: 'Technology Sector' },
      jobTitle: { ar: 'مطور أنظمة أول', en: 'Senior Systems Developer' },
      manager: '1003',
      managerName: { ar: 'خالد الغامدي', en: 'Khalid Al-Ghamdi' },
      empType: { ar: 'دوام كامل', en: 'Full-time' },
      workLocation: { ar: 'المقر الرئيسي - الرياض', en: 'Main Office - Riyadh' },
      shift: { ar: 'الفترة الصباحية 8:00 - 5:00', en: 'Morning Shift 8:00 - 5:00' },
      fingerprintId: 'FP-1001',
      contractStart: '2022-03-15',
      contractEnd: '2026-07-14',
      contractValue: '360,000',
      basicSalary: '18,000',
      allowances: { housing: '7,200', transport: '1,800', food: '1,000' },
      totalSalary: '28,000',
      bankName: { ar: 'البنك الأهلي السعودي', en: 'Saudi National Bank' },
      iban: 'SA12 8000 0000 1234 5678 9012',
      gosi: '1,980',
      leaveBalance: { annual: 22, sick: 30, used: 8, remaining: 14, carriedOver: 3 },
      status: 'active',
      avatar: '#ff9e18',
      hireDate: '2022-03-15',
      documents: [
        { name: { ar: 'الهوية الوطنية', en: 'National ID' }, status: 'valid', expiry: '2028-05-20', type: 'id' },
        { name: { ar: 'شهادة المؤهل', en: 'Qualification Certificate' }, status: 'valid', expiry: null, type: 'qualification' },
        { name: { ar: 'العنوان الوطني', en: 'National Address' }, status: 'valid', expiry: '2027-01-15', type: 'address' },
        { name: { ar: 'السيرة الذاتية', en: 'CV' }, status: 'valid', expiry: null, type: 'cv' },
        { name: { ar: 'عقد العمل', en: 'Employment Contract' }, status: 'valid', expiry: '2026-07-14', type: 'contract' },
        { name: { ar: 'شهادة البنك', en: 'Bank Certificate' }, status: 'valid', expiry: null, type: 'bank' },
        { name: { ar: 'التأمين الطبي', en: 'Medical Insurance' }, status: 'expiring', expiry: '2026-07-01', type: 'insurance' }
      ],
      performanceScore: 4.2,
      lastEvaluation: '2025-12-15',
      permissions: ['email', 'netsuite', 'vpn', 'laptop', 'access-card', 'door-fingerprint', 'server-access']
    },
    {
      id: '1002',
      nameAr: 'فاطمة بنت محمد الزهراني',
      nameEn: 'Fatima Mohammed Al-Zahrani',
      nationalId: '1087654321',
      nationality: { ar: 'سعودية', en: 'Saudi' },
      isSaudi: true,
      mobile: '+966 50 234 5678',
      email: 'fatima.zahrani@company.sa',
      nationalAddress: { ar: 'جدة - حي الشاطئ - شارع فلسطين', en: 'Jeddah - Al-Shati District - Palestine St' },
      qualification: { ar: 'ماجستير موارد بشرية', en: 'Master of Human Resources' },
      department: { ar: 'الموارد البشرية', en: 'Human Resources' },
      sector: { ar: 'الموارد البشرية', en: 'Human Resources' },
      jobTitle: { ar: 'أخصائية موارد بشرية', en: 'HR Specialist' },
      manager: '1004',
      managerName: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' },
      empType: { ar: 'دوام كامل', en: 'Full-time' },
      workLocation: { ar: 'فرع جدة', en: 'Jeddah Branch' },
      shift: { ar: 'الفترة الصباحية 8:00 - 5:00', en: 'Morning Shift 8:00 - 5:00' },
      fingerprintId: 'FP-1002',
      contractStart: '2021-06-01',
      contractEnd: '2026-05-31',
      contractValue: '288,000',
      basicSalary: '14,000',
      allowances: { housing: '5,600', transport: '1,400', food: '1,000' },
      totalSalary: '22,000',
      bankName: { ar: 'مصرف الراجحي', en: 'Al Rajhi Bank' },
      iban: 'SA98 2000 0000 9876 5432 1098',
      gosi: '1,540',
      leaveBalance: { annual: 22, sick: 30, used: 12, remaining: 10, carriedOver: 5 },
      status: 'active',
      avatar: '#7C3AED',
      hireDate: '2021-06-01',
      documents: [
        { name: { ar: 'الهوية الوطنية', en: 'National ID' }, status: 'valid', expiry: '2029-08-10', type: 'id' },
        { name: { ar: 'شهادة المؤهل', en: 'Qualification Certificate' }, status: 'valid', expiry: null, type: 'qualification' },
        { name: { ar: 'العنوان الوطني', en: 'National Address' }, status: 'missing', expiry: null, type: 'address' },
        { name: { ar: 'السيرة الذاتية', en: 'CV' }, status: 'valid', expiry: null, type: 'cv' },
        { name: { ar: 'عقد العمل', en: 'Employment Contract' }, status: 'valid', expiry: '2026-05-31', type: 'contract' },
        { name: { ar: 'شهادة البنك', en: 'Bank Certificate' }, status: 'valid', expiry: null, type: 'bank' },
        { name: { ar: 'التأمين الطبي', en: 'Medical Insurance' }, status: 'valid', expiry: '2027-03-15', type: 'insurance' }
      ],
      performanceScore: 4.5,
      lastEvaluation: '2025-12-15',
      permissions: ['email', 'netsuite', 'laptop', 'access-card', 'door-fingerprint']
    },
    {
      id: '1003',
      nameAr: 'خالد بن سعد الغامدي',
      nameEn: 'Khalid Saad Al-Ghamdi',
      nationalId: '1076543210',
      nationality: { ar: 'سعودي', en: 'Saudi' },
      isSaudi: true,
      mobile: '+966 54 345 6789',
      email: 'khalid.ghamdi@company.sa',
      nationalAddress: { ar: 'الرياض - حي النخيل - شارع أنس بن مالك', en: 'Riyadh - Al-Nakheel District - Anas Ibn Malik St' },
      qualification: { ar: 'ماجستير علوم حاسب', en: 'Master of Computer Science' },
      department: { ar: 'قطاع التقنية', en: 'Technology Sector' },
      sector: { ar: 'قطاع التقنية', en: 'Technology Sector' },
      jobTitle: { ar: 'مدير تقنية المعلومات', en: 'IT Manager' },
      manager: '1006',
      managerName: { ar: 'سلطان القحطاني', en: 'Sultan Al-Qahtani' },
      empType: { ar: 'دوام كامل', en: 'Full-time' },
      workLocation: { ar: 'المقر الرئيسي - الرياض', en: 'Main Office - Riyadh' },
      shift: { ar: 'الفترة الصباحية 8:00 - 5:00', en: 'Morning Shift 8:00 - 5:00' },
      fingerprintId: 'FP-1003',
      contractStart: '2020-01-10',
      contractEnd: '2026-01-09',
      contractValue: '540,000',
      basicSalary: '25,000',
      allowances: { housing: '10,000', transport: '2,500', food: '1,500' },
      totalSalary: '39,000',
      bankName: { ar: 'البنك السعودي الفرنسي', en: 'Saudi French Bank' },
      iban: 'SA55 5500 0000 5555 4444 3333',
      gosi: '2,750',
      leaveBalance: { annual: 30, sick: 30, used: 5, remaining: 25, carriedOver: 7 },
      status: 'active',
      avatar: '#2196F3',
      hireDate: '2020-01-10',
      documents: [
        { name: { ar: 'الهوية الوطنية', en: 'National ID' }, status: 'valid', expiry: '2027-11-25', type: 'id' },
        { name: { ar: 'شهادة المؤهل', en: 'Qualification Certificate' }, status: 'valid', expiry: null, type: 'qualification' },
        { name: { ar: 'العنوان الوطني', en: 'National Address' }, status: 'valid', expiry: '2027-06-30', type: 'address' },
        { name: { ar: 'عقد العمل', en: 'Employment Contract' }, status: 'expiring', expiry: '2026-01-09', type: 'contract' },
        { name: { ar: 'التأمين الطبي', en: 'Medical Insurance' }, status: 'valid', expiry: '2027-01-15', type: 'insurance' }
      ],
      performanceScore: 4.7,
      lastEvaluation: '2025-12-15',
      permissions: ['email', 'netsuite', 'vpn', 'laptop', 'access-card', 'door-fingerprint', 'server-access', 'admin-panel']
    },
    {
      id: '1004',
      nameAr: 'نورة بنت فهد العتيبي',
      nameEn: 'Noura Fahd Al-Otaibi',
      nationalId: '1065432109',
      nationality: { ar: 'سعودية', en: 'Saudi' },
      isSaudi: true,
      mobile: '+966 56 456 7890',
      email: 'noura.otaibi@company.sa',
      nationalAddress: { ar: 'الرياض - حي الياسمين', en: 'Riyadh - Al-Yasmin District' },
      qualification: { ar: 'ماجستير إدارة أعمال', en: 'MBA' },
      department: { ar: 'الموارد البشرية', en: 'Human Resources' },
      sector: { ar: 'الموارد البشرية', en: 'Human Resources' },
      jobTitle: { ar: 'مديرة الموارد البشرية', en: 'HR Manager' },
      manager: '1006',
      managerName: { ar: 'سلطان القحطاني', en: 'Sultan Al-Qahtani' },
      empType: { ar: 'دوام كامل', en: 'Full-time' },
      workLocation: { ar: 'المقر الرئيسي - الرياض', en: 'Main Office - Riyadh' },
      shift: { ar: 'الفترة الصباحية 8:00 - 5:00', en: 'Morning Shift 8:00 - 5:00' },
      fingerprintId: 'FP-1004',
      contractStart: '2019-09-01',
      contractEnd: '2027-08-31',
      contractValue: '600,000',
      basicSalary: '28,000',
      allowances: { housing: '11,200', transport: '2,800', food: '1,500' },
      totalSalary: '43,500',
      bankName: { ar: 'البنك الأهلي السعودي', en: 'Saudi National Bank' },
      iban: 'SA33 8000 0000 3333 2222 1111',
      gosi: '3,080',
      leaveBalance: { annual: 30, sick: 30, used: 15, remaining: 15, carriedOver: 0 },
      status: 'active',
      avatar: '#E91E63',
      hireDate: '2019-09-01',
      documents: [
        { name: { ar: 'الهوية الوطنية', en: 'National ID' }, status: 'valid', expiry: '2028-03-10', type: 'id' },
        { name: { ar: 'شهادة المؤهل', en: 'Qualification Certificate' }, status: 'valid', expiry: null, type: 'qualification' },
        { name: { ar: 'عقد العمل', en: 'Employment Contract' }, status: 'valid', expiry: '2027-08-31', type: 'contract' },
        { name: { ar: 'التأمين الطبي', en: 'Medical Insurance' }, status: 'valid', expiry: '2027-09-01', type: 'insurance' }
      ],
      performanceScore: 4.8,
      lastEvaluation: '2025-12-15',
      permissions: ['email', 'netsuite', 'vpn', 'laptop', 'access-card', 'door-fingerprint', 'hr-admin']
    },
    {
      id: '1005',
      nameAr: 'محمد بن يوسف الشمري',
      nameEn: 'Mohammed Yousuf Al-Shammari',
      nationalId: '2345678901',
      nationality: { ar: 'أردني', en: 'Jordanian' },
      isSaudi: false,
      iqamaNumber: '2345678901',
      iqamaExpiry: '2026-07-20',
      mobile: '+966 53 567 8901',
      email: 'mohammed.shammari@company.sa',
      nationalAddress: { ar: 'الرياض - حي الملقا', en: 'Riyadh - Al-Malqa District' },
      qualification: { ar: 'بكالوريوس محاسبة', en: 'Bachelor of Accounting' },
      department: { ar: 'الادارة المالية', en: 'Financial Management' },
      sector: { ar: 'الادارة المالية', en: 'Financial Management' },
      jobTitle: { ar: 'محاسب', en: 'Accountant' },
      manager: '1008',
      managerName: { ar: 'عبدالرحمن المطيري', en: 'Abdulrahman Al-Mutairi' },
      empType: { ar: 'دوام كامل', en: 'Full-time' },
      workLocation: { ar: 'المقر الرئيسي - الرياض', en: 'Main Office - Riyadh' },
      shift: { ar: 'الفترة الصباحية 8:00 - 5:00', en: 'Morning Shift 8:00 - 5:00' },
      fingerprintId: 'FP-1005',
      contractStart: '2023-04-01',
      contractEnd: '2026-03-31',
      contractValue: '216,000',
      basicSalary: '12,000',
      allowances: { housing: '4,800', transport: '1,200', food: '1,000' },
      totalSalary: '19,000',
      bankName: { ar: 'بنك الرياض', en: 'Riyad Bank' },
      iban: 'SA77 2000 0000 7777 6666 5555',
      gosi: '1,320',
      iqamaRenewalCost: '650',
      leaveBalance: { annual: 22, sick: 30, used: 4, remaining: 18, carriedOver: 0 },
      status: 'active',
      avatar: '#009688',
      hireDate: '2023-04-01',
      documents: [
        { name: { ar: 'الإقامة', en: 'Iqama' }, status: 'expiring', expiry: '2026-07-20', type: 'iqama' },
        { name: { ar: 'شهادة المؤهل', en: 'Qualification Certificate' }, status: 'valid', expiry: null, type: 'qualification' },
        { name: { ar: 'عقد العمل', en: 'Employment Contract' }, status: 'valid', expiry: '2026-03-31', type: 'contract' },
        { name: { ar: 'التأمين الطبي', en: 'Medical Insurance' }, status: 'valid', expiry: '2027-04-01', type: 'insurance' },
        { name: { ar: 'جواز السفر', en: 'Passport' }, status: 'valid', expiry: '2029-12-15', type: 'passport' }
      ],
      performanceScore: 3.8,
      lastEvaluation: '2025-12-15',
      permissions: ['email', 'netsuite', 'laptop', 'access-card', 'door-fingerprint']
    },
    {
      id: '1006',
      nameAr: 'سلطان بن عبدالعزيز القحطاني',
      nameEn: 'Sultan Abdulaziz Al-Qahtani',
      nationalId: '1054321098',
      nationality: { ar: 'سعودي', en: 'Saudi' },
      isSaudi: true,
      mobile: '+966 55 678 9012',
      email: 'sultan.qahtani@company.sa',
      nationalAddress: { ar: 'الرياض - حي الورود', en: 'Riyadh - Al-Wurood District' },
      qualification: { ar: 'دكتوراه إدارة أعمال', en: 'PhD in Business Administration' },
      department: { ar: 'الادارة التنفيذية', en: 'Executive Management' },
      sector: { ar: 'الادارة التنفيذية', en: 'Executive Management' },
      jobTitle: { ar: 'الرئيس التنفيذي', en: 'CEO / President' },
      manager: null,
      managerName: null,
      empType: { ar: 'دوام كامل', en: 'Full-time' },
      workLocation: { ar: 'المقر الرئيسي - الرياض', en: 'Main Office - Riyadh' },
      shift: { ar: 'مرن', en: 'Flexible' },
      fingerprintId: 'FP-1006',
      contractStart: '2018-01-01',
      contractEnd: '2028-12-31',
      contractValue: '1,200,000',
      basicSalary: '55,000',
      allowances: { housing: '22,000', transport: '5,500', food: '2,000' },
      totalSalary: '84,500',
      bankName: { ar: 'البنك السعودي البريطاني', en: 'SABB' },
      iban: 'SA88 4500 0000 8888 7777 6666',
      gosi: '4,000',
      leaveBalance: { annual: 30, sick: 30, used: 10, remaining: 20, carriedOver: 5 },
      status: 'active',
      avatar: '#0B192C',
      hireDate: '2018-01-01',
      documents: [
        { name: { ar: 'الهوية الوطنية', en: 'National ID' }, status: 'valid', expiry: '2030-06-15', type: 'id' },
        { name: { ar: 'عقد العمل', en: 'Employment Contract' }, status: 'valid', expiry: '2028-12-31', type: 'contract' },
        { name: { ar: 'التأمين الطبي', en: 'Medical Insurance' }, status: 'valid', expiry: '2027-01-01', type: 'insurance' }
      ],
      performanceScore: 4.9,
      lastEvaluation: '2025-12-15',
      permissions: ['email', 'netsuite', 'vpn', 'laptop', 'access-card', 'door-fingerprint', 'server-access', 'admin-panel', 'executive-dashboard']
    },
    {
      id: '1007',
      nameAr: 'عبدالله بن فيصل الدوسري',
      nameEn: 'Abdullah Faisal Al-Dosari',
      nationalId: '1043210987',
      nationality: { ar: 'سعودي', en: 'Saudi' },
      isSaudi: true,
      mobile: '+966 50 789 0123',
      email: 'abdullah.dosari@company.sa',
      nationalAddress: { ar: 'الدمام - حي الفيصلية', en: 'Dammam - Al-Faisaliah District' },
      qualification: { ar: 'بكالوريوس تكنولوجيا التعليم', en: 'BSc Educational Technology' },
      department: { ar: 'قطاع التعليم', en: 'Education Sector' },
      sector: { ar: 'قطاع التعليم', en: 'Education Sector' },
      jobTitle: { ar: 'مسؤول تقنيات التعليم', en: 'Educational Technology Officer' },
      manager: '1004',
      managerName: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' },
      empType: { ar: 'دوام كامل', en: 'Full-time' },
      workLocation: { ar: 'المقر الرئيسي - الرياض', en: 'Main Office - Riyadh' },
      shift: { ar: 'الفترة الصباحية 8:00 - 5:00', en: 'Morning Shift 8:00 - 5:00' },
      fingerprintId: 'FP-1007',
      contractStart: '2022-08-01',
      contractEnd: '2026-07-31',
      contractValue: '264,000',
      basicSalary: '13,000',
      allowances: { housing: '5,200', transport: '1,300', food: '1,000' },
      totalSalary: '20,500',
      bankName: { ar: 'البنك الأهلي السعودي', en: 'Saudi National Bank' },
      iban: 'SA22 8000 0000 2222 1111 0000',
      gosi: '1,430',
      leaveBalance: { annual: 22, sick: 30, used: 6, remaining: 16, carriedOver: 2 },
      status: 'active',
      avatar: '#4CAF50',
      hireDate: '2022-08-01',
      documents: [
        { name: { ar: 'الهوية الوطنية', en: 'National ID' }, status: 'valid', expiry: '2028-09-10', type: 'id' },
        { name: { ar: 'عقد العمل', en: 'Employment Contract' }, status: 'valid', expiry: '2026-07-31', type: 'contract' },
        { name: { ar: 'التأمين الطبي', en: 'Medical Insurance' }, status: 'missing', expiry: null, type: 'insurance' }
      ],
      performanceScore: 3.9,
      lastEvaluation: '2025-12-15',
      permissions: ['email', 'vpn', 'laptop', 'access-card', 'door-fingerprint']
    },
    {
      id: '1008',
      nameAr: 'عبدالرحمن بن سعود المطيري',
      nameEn: 'Abdulrahman Saud Al-Mutairi',
      nationalId: '1032109876',
      nationality: { ar: 'سعودي', en: 'Saudi' },
      isSaudi: true,
      mobile: '+966 54 890 1234',
      email: 'abdulrahman.mutairi@company.sa',
      nationalAddress: { ar: 'الرياض - حي الصحافة', en: 'Riyadh - Al-Sahafa District' },
      qualification: { ar: 'ماجستير محاسبة', en: 'Master of Accounting' },
      department: { ar: 'الادارة المالية', en: 'Financial Management' },
      sector: { ar: 'الادارة المالية', en: 'Financial Management' },
      jobTitle: { ar: 'المدير المالي', en: 'Finance Manager' },
      manager: '1006',
      managerName: { ar: 'سلطان القحطاني', en: 'Sultan Al-Qahtani' },
      empType: { ar: 'دوام كامل', en: 'Full-time' },
      workLocation: { ar: 'المقر الرئيسي - الرياض', en: 'Main Office - Riyadh' },
      shift: { ar: 'الفترة الصباحية 8:00 - 5:00', en: 'Morning Shift 8:00 - 5:00' },
      fingerprintId: 'FP-1008',
      contractStart: '2019-05-15',
      contractEnd: '2027-05-14',
      contractValue: '480,000',
      basicSalary: '22,000',
      allowances: { housing: '8,800', transport: '2,200', food: '1,500' },
      totalSalary: '34,500',
      bankName: { ar: 'البنك السعودي الفرنسي', en: 'Saudi French Bank' },
      iban: 'SA44 5500 0000 4444 3333 2222',
      gosi: '2,420',
      leaveBalance: { annual: 30, sick: 30, used: 18, remaining: 12, carriedOver: 4 },
      status: 'active',
      avatar: '#795548',
      hireDate: '2019-05-15',
      documents: [
        { name: { ar: 'الهوية الوطنية', en: 'National ID' }, status: 'valid', expiry: '2029-02-20', type: 'id' },
        { name: { ar: 'عقد العمل', en: 'Employment Contract' }, status: 'valid', expiry: '2027-05-14', type: 'contract' },
        { name: { ar: 'التأمين الطبي', en: 'Medical Insurance' }, status: 'valid', expiry: '2027-05-15', type: 'insurance' }
      ],
      performanceScore: 4.4,
      lastEvaluation: '2025-12-15',
      permissions: ['email', 'netsuite', 'vpn', 'laptop', 'access-card', 'door-fingerprint', 'finance-admin']
    },
    {
      id: '1009',
      nameAr: 'سارة بنت خالد العنزي',
      nameEn: 'Sara Khalid Al-Anzi',
      nationalId: '1021098765',
      nationality: { ar: 'سعودية', en: 'Saudi' },
      isSaudi: true,
      mobile: '+966 55 901 2345',
      email: 'sara.anzi@company.sa',
      nationalAddress: { ar: 'الرياض - حي الربيع', en: 'Riyadh - Al-Rabie District' },
      qualification: { ar: 'بكالوريوس تسويق', en: 'Bachelor of Marketing' },
      department: { ar: 'قطاع الفعاليات والمؤتمرات', en: 'Events & Conferences Sector' },
      sector: { ar: 'قطاع الفعاليات والمؤتمرات', en: 'Events & Conferences Sector' },
      jobTitle: { ar: 'أخصائية فعاليات وتسويق', en: 'Events & Marketing Specialist' },
      manager: '1008',
      managerName: { ar: 'عبدالرحمن المطيري', en: 'Abdulrahman Al-Mutairi' },
      empType: { ar: 'عن بعد', en: 'Remote' },
      workLocation: { ar: 'عن بعد', en: 'Remote' },
      shift: { ar: 'مرن', en: 'Flexible' },
      fingerprintId: 'FP-1009',
      contractStart: '2024-01-15',
      contractEnd: '2026-01-14',
      contractValue: '180,000',
      basicSalary: '10,000',
      allowances: { housing: '4,000', transport: '1,000', food: '800' },
      totalSalary: '15,800',
      bankName: { ar: 'مصرف الراجحي', en: 'Al Rajhi Bank' },
      iban: 'SA66 2000 0000 6666 5555 4444',
      gosi: '1,100',
      leaveBalance: { annual: 22, sick: 30, used: 2, remaining: 20, carriedOver: 0 },
      status: 'on-leave',
      avatar: '#FF5722',
      hireDate: '2024-01-15',
      documents: [
        { name: { ar: 'الهوية الوطنية', en: 'National ID' }, status: 'valid', expiry: '2028-07-05', type: 'id' },
        { name: { ar: 'عقد العمل', en: 'Employment Contract' }, status: 'expiring', expiry: '2026-01-14', type: 'contract' },
        { name: { ar: 'التأمين الطبي', en: 'Medical Insurance' }, status: 'missing', expiry: null, type: 'insurance' },
        { name: { ar: 'السيرة الذاتية', en: 'CV' }, status: 'missing', expiry: null, type: 'cv' }
      ],
      performanceScore: 4.0,
      lastEvaluation: '2025-12-15',
      permissions: ['email', 'netsuite', 'vpn', 'laptop']
    },
    {
      id: '1010',
      nameAr: 'ياسر بن حسن الشهري',
      nameEn: 'Yasser Hassan Al-Shahri',
      nationalId: '1010987654',
      nationality: { ar: 'سعودي', en: 'Saudi' },
      isSaudi: true,
      mobile: '+966 53 012 3456',
      email: 'yasser.shahri@company.sa',
      nationalAddress: { ar: 'أبها - حي المنسك', en: 'Abha - Al-Mansak District' },
      qualification: { ar: 'دبلوم إداري', en: 'Administrative Diploma' },
      department: { ar: 'قطاع التشغيل', en: 'Operations Sector' },
      sector: { ar: 'قطاع التشغيل', en: 'Operations Sector' },
      jobTitle: { ar: 'موظف استقبال', en: 'Receptionist' },
      manager: '1004',
      managerName: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' },
      empType: { ar: 'دوام جزئي', en: 'Part-time' },
      workLocation: { ar: 'المقر الرئيسي - الرياض', en: 'Main Office - Riyadh' },
      shift: { ar: 'الفترة المسائية 1:00 - 6:00', en: 'Evening Shift 1:00 - 6:00' },
      fingerprintId: 'FP-1010',
      contractStart: '2025-03-01',
      contractEnd: '2026-02-28',
      contractValue: '84,000',
      basicSalary: '6,000',
      allowances: { housing: '2,400', transport: '600', food: '500' },
      totalSalary: '9,500',
      bankName: null,
      iban: null,
      gosi: '660',
      leaveBalance: { annual: 22, sick: 30, used: 0, remaining: 22, carriedOver: 0 },
      status: 'probation',
      avatar: '#607D8B',
      hireDate: '2025-03-01',
      documents: [
        { name: { ar: 'الهوية الوطنية', en: 'National ID' }, status: 'valid', expiry: '2029-10-10', type: 'id' },
        { name: { ar: 'عقد العمل', en: 'Employment Contract' }, status: 'valid', expiry: '2026-02-28', type: 'contract' },
        { name: { ar: 'شهادة المؤهل', en: 'Qualification Certificate' }, status: 'missing', expiry: null, type: 'qualification' },
        { name: { ar: 'التأمين الطبي', en: 'Medical Insurance' }, status: 'valid', expiry: '2026-03-01', type: 'insurance' }
      ],
      performanceScore: null,
      lastEvaluation: null,
      permissions: ['email', 'access-card', 'door-fingerprint']
    }
  ],

  // ==========================================
  // REQUESTS
  // ==========================================
  requests: [
    {
      id: 'REQ-2026-001',
      type: 'leave',
      typeLabel: { ar: 'طلب إجازة', en: 'Leave Request' },
      employeeId: '1001',
      employeeName: { ar: 'أحمد الحربي', en: 'Ahmed Al-Harbi' },
      department: { ar: 'قطاع التقنية', en: 'Technology Sector' },
      initiator: { ar: 'أحمد الحربي', en: 'Ahmed Al-Harbi' },
      status: 'pending',
      statusLabel: { ar: 'قيد الموافقة', en: 'Pending Approval' },
      currentApprover: { ar: 'خالد الغامدي', en: 'Khalid Al-Ghamdi' },
      createdDate: '2026-06-05',
      updatedDate: '2026-06-05',
      data: {
        leaveType: { ar: 'إجازة سنوية', en: 'Annual Leave' },
        startDate: '2026-07-01',
        endDate: '2026-07-10',
        days: 10,
        reason: { ar: 'إجازة عائلية', en: 'Family vacation' },
        substitute: { ar: 'عبدالله الدوسري', en: 'Abdullah Al-Dosari' },
        contact: '+966 55 123 4567'
      },
      workflow: [
        { role: { ar: 'الموظف', en: 'Employee' }, name: { ar: 'أحمد الحربي', en: 'Ahmed Al-Harbi' }, status: 'completed', date: '2026-06-05', comment: { ar: 'تم تقديم الطلب', en: 'Request submitted' } },
        { role: { ar: 'المدير المباشر', en: 'Direct Manager' }, name: { ar: 'خالد الغامدي', en: 'Khalid Al-Ghamdi' }, status: 'current', date: null, comment: null },
        { role: { ar: 'أخصائي الموارد البشرية', en: 'HR Specialist' }, name: { ar: 'فاطمة الزهراني', en: 'Fatima Al-Zahrani' }, status: 'pending', date: null, comment: null },
        { role: { ar: 'مدير الموارد البشرية', en: 'HR Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'pending', date: null, comment: null },
        { role: { ar: 'الرئيس التنفيذي', en: 'CEO' }, name: { ar: 'سلطان القحطاني', en: 'Sultan Al-Qahtani' }, status: 'pending', date: null, comment: null }
      ],
      attachments: [],
      notifications: ['submitted', 'pending-manager'],
      reportsUpdated: ['leave-balance', 'team-availability']
    },
    {
      id: 'REQ-2026-002',
      type: 'overtime',
      typeLabel: { ar: 'طلب عمل إضافي', en: 'Overtime Request' },
      employeeId: '1001',
      employeeName: { ar: 'أحمد الحربي', en: 'Ahmed Al-Harbi' },
      department: { ar: 'قطاع التقنية', en: 'Technology Sector' },
      initiator: { ar: 'خالد الغامدي', en: 'Khalid Al-Ghamdi' },
      status: 'approved',
      statusLabel: { ar: 'معتمد', en: 'Approved' },
      currentApprover: null,
      createdDate: '2026-05-20',
      updatedDate: '2026-05-25',
      data: {
        date: '2026-05-22',
        startTime: '17:00',
        endTime: '21:00',
        hours: 4,
        description: { ar: 'إنهاء مشروع ترقية الأنظمة', en: 'Complete system upgrade project' },
        overtimeType: { ar: 'يوم عادي', en: 'Normal Day' },
        compensationType: { ar: 'عمل إضافي مدفوع', en: 'Paid Overtime' }
      },
      workflow: [
        { role: { ar: 'المدير المباشر', en: 'Direct Manager' }, name: { ar: 'خالد الغامدي', en: 'Khalid Al-Ghamdi' }, status: 'completed', date: '2026-05-20', comment: { ar: 'مطلوب لإنهاء المشروع', en: 'Required for project completion' } },
        { role: { ar: 'أخصائي الموارد البشرية', en: 'HR Specialist' }, name: { ar: 'فاطمة الزهراني', en: 'Fatima Al-Zahrani' }, status: 'completed', date: '2026-05-21', comment: null },
        { role: { ar: 'مدير الموارد البشرية', en: 'HR Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'completed', date: '2026-05-22', comment: null },
        { role: { ar: 'الرئيس التنفيذي', en: 'CEO' }, name: { ar: 'سلطان القحطاني', en: 'Sultan Al-Qahtani' }, status: 'completed', date: '2026-05-24', comment: { ar: 'موافق', en: 'Approved' } },
        { role: { ar: 'مدير الموارد البشرية', en: 'HR Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'completed', date: '2026-05-25', comment: { ar: 'تمت الإضافة للرواتب', en: 'Added to payroll' } }
      ],
      attachments: [],
      notifications: ['submitted', 'approved', 'payroll-updated'],
      reportsUpdated: ['overtime-hours', 'overtime-cost', 'payroll']
    },
    {
      id: 'REQ-2026-003',
      type: 'sick-leave',
      typeLabel: { ar: 'إجازة مرضية', en: 'Sick Leave' },
      employeeId: '1005',
      employeeName: { ar: 'محمد الشمري', en: 'Mohammed Al-Shammari' },
      department: { ar: 'الادارة المالية', en: 'Financial Management' },
      initiator: { ar: 'محمد الشمري', en: 'Mohammed Al-Shammari' },
      status: 'approved',
      statusLabel: { ar: 'معتمد', en: 'Approved' },
      currentApprover: null,
      createdDate: '2026-06-01',
      updatedDate: '2026-06-02',
      data: {
        leaveType: { ar: 'إجازة مرضية', en: 'Sick Leave' },
        startDate: '2026-06-01',
        endDate: '2026-06-03',
        days: 3,
        reason: { ar: 'مراجعة طبية', en: 'Medical check-up' }
      },
      workflow: [
        { role: { ar: 'الموظف', en: 'Employee' }, name: { ar: 'محمد الشمري', en: 'Mohammed Al-Shammari' }, status: 'completed', date: '2026-06-01', comment: null },
        { role: { ar: 'أخصائي الموارد البشرية', en: 'HR Specialist' }, name: { ar: 'فاطمة الزهراني', en: 'Fatima Al-Zahrani' }, status: 'completed', date: '2026-06-01', comment: null },
        { role: { ar: 'مدير الموارد البشرية', en: 'HR Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'completed', date: '2026-06-02', comment: { ar: 'موافق', en: 'Approved' } }
      ],
      attachments: [{ name: { ar: 'تقرير طبي', en: 'Medical Report' }, type: 'pdf' }],
      notifications: ['submitted', 'approved', 'leave-updated'],
      reportsUpdated: ['leave-balance', 'leave-usage']
    },
    {
      id: 'REQ-2026-004',
      type: 'salary-certificate',
      typeLabel: { ar: 'شهادة راتب', en: 'Salary Certificate' },
      employeeId: '1009',
      employeeName: { ar: 'سارة العنزي', en: 'Sara Al-Anzi' },
      department: { ar: 'قطاع الفعاليات والمؤتمرات', en: 'Events & Conferences Sector' },
      initiator: { ar: 'سارة العنزي', en: 'Sara Al-Anzi' },
      status: 'completed',
      statusLabel: { ar: 'مكتمل', en: 'Completed' },
      currentApprover: null,
      createdDate: '2026-05-28',
      updatedDate: '2026-05-30',
      data: {
        purpose: { ar: 'تقديم لبنك', en: 'Bank application' },
        recipient: { ar: 'البنك الأهلي', en: 'Saudi National Bank' },
        language: { ar: 'عربي', en: 'Arabic' },
        salaryVisible: true,
        digitalStamp: true
      },
      workflow: [
        { role: { ar: 'الموظف', en: 'Employee' }, name: { ar: 'سارة العنزي', en: 'Sara Al-Anzi' }, status: 'completed', date: '2026-05-28', comment: null },
        { role: { ar: 'أخصائي الموارد البشرية', en: 'HR Specialist' }, name: { ar: 'فاطمة الزهراني', en: 'Fatima Al-Zahrani' }, status: 'completed', date: '2026-05-29', comment: null },
        { role: { ar: 'مدير الموارد البشرية', en: 'HR Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'completed', date: '2026-05-30', comment: { ar: 'تم إصدار الشهادة', en: 'Certificate issued' } }
      ],
      attachments: [{ name: { ar: 'شهادة الراتب.pdf', en: 'Salary_Certificate.pdf' }, type: 'pdf' }],
      notifications: ['submitted', 'approved', 'certificate-ready'],
      reportsUpdated: ['hr-letters']
    },
    {
      id: 'REQ-2026-005',
      type: 'attendance-correction',
      typeLabel: { ar: 'تصحيح حضور', en: 'Attendance Correction' },
      employeeId: '1010',
      employeeName: { ar: 'ياسر الشهري', en: 'Yasser Al-Shahri' },
      department: { ar: 'قطاع التشغيل', en: 'Operations Sector' },
      initiator: { ar: 'ياسر الشهري', en: 'Yasser Al-Shahri' },
      status: 'pending',
      statusLabel: { ar: 'قيد الموافقة', en: 'Pending Approval' },
      currentApprover: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' },
      createdDate: '2026-06-08',
      updatedDate: '2026-06-08',
      data: {
        date: '2026-06-07',
        punchType: { ar: 'تسجيل خروج', en: 'Check-out' },
        actualTime: '18:00',
        reason: { ar: 'نسيت تسجيل الخروج', en: 'Forgot to check out' }
      },
      workflow: [
        { role: { ar: 'الموظف', en: 'Employee' }, name: { ar: 'ياسر الشهري', en: 'Yasser Al-Shahri' }, status: 'completed', date: '2026-06-08', comment: null },
        { role: { ar: 'المدير المباشر', en: 'Direct Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'current', date: null, comment: null },
        { role: { ar: 'أخصائي الموارد البشرية', en: 'HR Specialist' }, name: { ar: 'فاطمة الزهراني', en: 'Fatima Al-Zahrani' }, status: 'pending', date: null, comment: null },
        { role: { ar: 'مدير الموارد البشرية', en: 'HR Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'pending', date: null, comment: null }
      ],
      attachments: [],
      notifications: ['submitted', 'pending-manager'],
      reportsUpdated: ['attendance-exceptions']
    },
    {
      id: 'REQ-2026-006',
      type: 'remote-work',
      typeLabel: { ar: 'طلب عمل عن بعد', en: 'Remote Work Request' },
      employeeId: '1001',
      employeeName: { ar: 'أحمد الحربي', en: 'Ahmed Al-Harbi' },
      department: { ar: 'قطاع التقنية', en: 'Technology Sector' },
      initiator: { ar: 'أحمد الحربي', en: 'Ahmed Al-Harbi' },
      status: 'rejected',
      statusLabel: { ar: 'مرفوض', en: 'Rejected' },
      currentApprover: null,
      createdDate: '2026-05-15',
      updatedDate: '2026-05-17',
      data: {
        dateRange: '2026-05-20 - 2026-05-24',
        reason: { ar: 'ظروف شخصية', en: 'Personal circumstances' },
        location: { ar: 'المنزل - الرياض', en: 'Home - Riyadh' },
        tasks: { ar: 'تطوير واجهات النظام الجديد', en: 'Developing new system interfaces' },
        contactAvailable: true
      },
      workflow: [
        { role: { ar: 'الموظف', en: 'Employee' }, name: { ar: 'أحمد الحربي', en: 'Ahmed Al-Harbi' }, status: 'completed', date: '2026-05-15', comment: null },
        { role: { ar: 'المدير المباشر', en: 'Direct Manager' }, name: { ar: 'خالد الغامدي', en: 'Khalid Al-Ghamdi' }, status: 'completed', date: '2026-05-16', comment: { ar: 'موافق', en: 'Approved' } },
        { role: { ar: 'مدير الموارد البشرية', en: 'HR Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'rejected', date: '2026-05-17', comment: { ar: 'يتطلب حضور شخصي لاجتماعات المشروع', en: 'In-person attendance required for project meetings' } }
      ],
      attachments: [],
      notifications: ['submitted', 'rejected'],
      reportsUpdated: []
    },
    {
      id: 'REQ-2026-007',
      type: 'bank-change',
      typeLabel: { ar: 'تغيير حساب بنكي', en: 'Bank Account Change' },
      employeeId: '1002',
      employeeName: { ar: 'فاطمة الزهراني', en: 'Fatima Al-Zahrani' },
      department: { ar: 'الموارد البشرية', en: 'Human Resources' },
      initiator: { ar: 'فاطمة الزهراني', en: 'Fatima Al-Zahrani' },
      status: 'approved',
      statusLabel: { ar: 'معتمد', en: 'Approved' },
      currentApprover: null,
      createdDate: '2026-05-10',
      updatedDate: '2026-05-12',
      data: {
        bankName: { ar: 'البنك الأهلي السعودي', en: 'Saudi National Bank' },
        newIban: 'SA12 8000 0000 9999 8888 7777',
        effectiveDate: '2026-06-01',
        reason: { ar: 'تحويل الراتب لحساب جديد', en: 'Transfer salary to new account' }
      },
      workflow: [
        { role: { ar: 'الموظف', en: 'Employee' }, name: { ar: 'فاطمة الزهراني', en: 'Fatima Al-Zahrani' }, status: 'completed', date: '2026-05-10', comment: null },
        { role: { ar: 'المدير المباشر', en: 'Direct Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'completed', date: '2026-05-11', comment: null },
        { role: { ar: 'مدير الموارد البشرية', en: 'HR Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'completed', date: '2026-05-12', comment: { ar: 'تم التحديث', en: 'Updated' } }
      ],
      attachments: [{ name: { ar: 'شهادة الآيبان', en: 'IBAN Certificate' }, type: 'pdf' }],
      notifications: ['submitted', 'approved', 'payroll-updated'],
      reportsUpdated: ['payroll-master', 'sensitive-changes']
    },
    {
      id: 'REQ-2026-008',
      type: 'business-card',
      typeLabel: { ar: 'طلب بطاقة عمل', en: 'Business Card Request' },
      employeeId: '1001',
      employeeName: { ar: 'أحمد الحربي', en: 'Ahmed Al-Harbi' },
      department: { ar: 'قطاع التقنية', en: 'Technology Sector' },
      initiator: { ar: 'خالد الغامدي', en: 'Khalid Al-Ghamdi' },
      status: 'in-progress',
      statusLabel: { ar: 'قيد التنفيذ', en: 'In Progress' },
      currentApprover: { ar: 'عبدالله الدوسري', en: 'Abdullah Al-Dosari' },
      createdDate: '2026-06-03',
      updatedDate: '2026-06-06',
      data: {
        employeeName: { ar: 'أحمد بن عبدالله الحربي', en: 'Ahmed Abdullah Al-Harbi' },
        jobTitle: { ar: 'مطور أنظمة أول', en: 'Senior Systems Developer' },
        department: { ar: 'قطاع التقنية', en: 'Technology Sector' },
        mobile: '+966 55 123 4567',
        email: 'ahmed.harbi@company.sa',
        quantity: 200,
        language: { ar: 'عربي - إنجليزي', en: 'Arabic - English' },
        deliveryLocation: { ar: 'المقر الرئيسي', en: 'Main Office' }
      },
      workflow: [
        { role: { ar: 'المدير المباشر', en: 'Direct Manager' }, name: { ar: 'خالد الغامدي', en: 'Khalid Al-Ghamdi' }, status: 'completed', date: '2026-06-03', comment: null },
        { role: { ar: 'مسؤول تقنيات التعليم', en: 'Educational Technology Officer' }, name: { ar: 'عبدالله الدوسري', en: 'Abdullah Al-Dosari' }, status: 'current', date: null, comment: null },
        { role: { ar: 'مدير الموارد البشرية', en: 'HR Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'pending', date: null, comment: null },
        { role: { ar: 'مقدم الطلب', en: 'Request Creator' }, name: { ar: 'خالد الغامدي', en: 'Khalid Al-Ghamdi' }, status: 'pending', date: null, comment: null }
      ],
      attachments: [],
      notifications: ['submitted', 'pending-it'],
      reportsUpdated: ['business-card-requests']
    },
    {
      id: 'REQ-2026-009',
      type: 'warning',
      typeLabel: { ar: 'إنذار إداري', en: 'Warning Notice' },
      employeeId: '1010',
      employeeName: { ar: 'ياسر الشهري', en: 'Yasser Al-Shahri' },
      department: { ar: 'قطاع التشغيل', en: 'Operations Sector' },
      initiator: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' },
      status: 'pending',
      statusLabel: { ar: 'بانتظار إقرار الموظف', en: 'Awaiting Employee Acknowledgment' },
      currentApprover: { ar: 'ياسر الشهري', en: 'Yasser Al-Shahri' },
      createdDate: '2026-06-07',
      updatedDate: '2026-06-08',
      data: {
        violationType: { ar: 'تأخر متكرر', en: 'Repeated Tardiness' },
        incidentDate: '2026-06-06',
        description: { ar: 'تأخر عن الحضور لمدة 3 أيام متتالية بدون إذن مسبق', en: 'Late arrival for 3 consecutive days without prior permission' },
        actionRequired: { ar: 'إنذار كتابي أول', en: 'First Written Warning' }
      },
      workflow: [
        { role: { ar: 'المدير المباشر / الموارد البشرية', en: 'Direct Manager / HR' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'completed', date: '2026-06-07', comment: null },
        { role: { ar: 'أخصائي الموارد البشرية', en: 'HR Specialist' }, name: { ar: 'فاطمة الزهراني', en: 'Fatima Al-Zahrani' }, status: 'completed', date: '2026-06-07', comment: null },
        { role: { ar: 'مدير الموارد البشرية', en: 'HR Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'completed', date: '2026-06-08', comment: { ar: 'تمت الموافقة على إصدار الإنذار', en: 'Warning approved' } },
        { role: { ar: 'إقرار الموظف', en: 'Employee Acknowledgment' }, name: { ar: 'ياسر الشهري', en: 'Yasser Al-Shahri' }, status: 'current', date: null, comment: null }
      ],
      attachments: [{ name: { ar: 'سجل الحضور', en: 'Attendance Log' }, type: 'pdf' }],
      notifications: ['submitted', 'approved', 'pending-acknowledgment'],
      reportsUpdated: ['warnings', 'employee-disciplinary']
    },
    {
      id: 'REQ-2026-010',
      type: 'resignation',
      typeLabel: { ar: 'طلب استقالة', en: 'Resignation Request' },
      employeeId: '1005',
      employeeName: { ar: 'محمد الشمري', en: 'Mohammed Al-Shammari' },
      department: { ar: 'الادارة المالية', en: 'Financial Management' },
      initiator: { ar: 'محمد الشمري', en: 'Mohammed Al-Shammari' },
      status: 'in-progress',
      statusLabel: { ar: 'قيد المعالجة', en: 'In Progress' },
      currentApprover: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' },
      createdDate: '2026-06-01',
      updatedDate: '2026-06-05',
      data: {
        lastWorkingDay: '2026-07-01',
        reason: { ar: 'فرصة عمل أخرى', en: 'Another job opportunity' },
        noticePeriod: { ar: '30 يوم', en: '30 days' },
        handoverNotes: { ar: 'سيتم تسليم جميع المهام للزميل أحمد', en: 'All tasks will be handed over to colleague Ahmed' }
      },
      workflow: [
        { role: { ar: 'الموظف', en: 'Employee' }, name: { ar: 'محمد الشمري', en: 'Mohammed Al-Shammari' }, status: 'completed', date: '2026-06-01', comment: null },
        { role: { ar: 'المدير المباشر', en: 'Direct Manager' }, name: { ar: 'عبدالرحمن المطيري', en: 'Abdulrahman Al-Mutairi' }, status: 'completed', date: '2026-06-02', comment: { ar: 'تمت المحاولة للاحتفاظ بالموظف', en: 'Retention attempt made' } },
        { role: { ar: 'مدير الموارد البشرية', en: 'HR Manager' }, name: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' }, status: 'current', date: null, comment: null },
        { role: { ar: 'الرئيس التنفيذي', en: 'CEO' }, name: { ar: 'سلطان القحطاني', en: 'Sultan Al-Qahtani' }, status: 'pending', date: null, comment: null }
      ],
      attachments: [{ name: { ar: 'خطاب الاستقالة', en: 'Resignation Letter' }, type: 'pdf' }],
      notifications: ['submitted', 'pending-hr'],
      reportsUpdated: ['resignation', 'end-of-service']
    }
  ],

  // ==========================================
  // NOTIFICATIONS
  // ==========================================
  notifications: [
    { id: 1, type: 'request', icon: '📋', titleAr: 'طلب إجازة جديد', titleEn: 'New Leave Request', descAr: 'أحمد الحربي قدّم طلب إجازة سنوية من 01/07 إلى 10/07', descEn: 'Ahmed Al-Harbi submitted annual leave from 07/01 to 07/10', time: '2026-06-05T09:30:00', read: false, bgColor: 'var(--accent-orange-light)' },
    { id: 2, type: 'approval', icon: '✅', titleAr: 'تمت الموافقة على العمل الإضافي', titleEn: 'Overtime Approved', descAr: 'تمت الموافقة على طلب العمل الإضافي REQ-2026-002 وإضافته للرواتب', descEn: 'Overtime request REQ-2026-002 approved and added to payroll', time: '2026-06-05T10:15:00', read: false, bgColor: 'var(--success-light)' },
    { id: 3, type: 'document', icon: '📄', titleAr: 'مستند يقارب انتهاء الصلاحية', titleEn: 'Document Expiring Soon', descAr: 'التأمين الطبي لـ أحمد الحربي ينتهي في 01/07/2026', descEn: 'Medical insurance for Ahmed Al-Harbi expires on 07/01/2026', time: '2026-06-04T14:00:00', read: true, bgColor: 'var(--warning-light)' },
    { id: 4, type: 'contract', icon: '📝', titleAr: 'عقد يقارب انتهاء الصلاحية', titleEn: 'Contract Expiring Soon', descAr: 'عقد سارة العنزي ينتهي في 14/01/2026 - يجب التجديد', descEn: 'Sara Al-Anzi contract expires on 01/14/2026 - renewal needed', time: '2026-06-03T08:00:00', read: true, bgColor: 'var(--danger-light)' },
    { id: 5, type: 'warning', icon: '⚠️', titleAr: 'إنذار إداري صادر', titleEn: 'Warning Notice Issued', descAr: 'تم إصدار إنذار كتابي أول لـ ياسر الشهري بسبب التأخر المتكرر', descEn: 'First written warning issued to Yasser Al-Shahri for repeated tardiness', time: '2026-06-08T11:00:00', read: false, bgColor: 'var(--danger-light)' },
    { id: 6, type: 'certificate', icon: '🏆', titleAr: 'شهادة الراتب جاهزة', titleEn: 'Salary Certificate Ready', descAr: 'شهادة الراتب لـ سارة العنزي جاهزة للتحميل', descEn: 'Salary certificate for Sara Al-Anzi is ready for download', time: '2026-05-30T16:00:00', read: true, bgColor: 'var(--info-light)' },
    { id: 7, type: 'resignation', icon: '🚪', titleAr: 'طلب استقالة', titleEn: 'Resignation Request', descAr: 'محمد الشمري قدّم طلب استقالة - آخر يوم عمل 01/07/2026', descEn: 'Mohammed Al-Shammari submitted resignation - last day 07/01/2026', time: '2026-06-01T09:00:00', read: true, bgColor: 'var(--purple-light)' },
    { id: 8, type: 'evaluation', icon: '📊', titleAr: 'دورة تقييم جديدة', titleEn: 'New Evaluation Cycle', descAr: 'تم بدء دورة التقييم السنوية للنصف الأول 2026', descEn: 'Annual evaluation cycle for H1 2026 has started', time: '2026-06-01T08:00:00', read: true, bgColor: 'var(--purple-light)' },
    { id: 9, type: 'attendance', icon: '🕐', titleAr: 'مشكلة حضور', titleEn: 'Attendance Issue', descAr: 'ياسر الشهري - تسجيل خروج مفقود بتاريخ 07/06', descEn: 'Yasser Al-Shahri - missing check-out on 06/07', time: '2026-06-08T07:00:00', read: false, bgColor: 'var(--warning-light)' },
    { id: 10, type: 'bank', icon: '🏦', titleAr: 'تم تحديث الحساب البنكي', titleEn: 'Bank Account Updated', descAr: 'تم تحديث بيانات الحساب البنكي لـ فاطمة الزهراني', descEn: 'Bank details updated for Fatima Al-Zahrani', time: '2026-05-12T13:00:00', read: true, bgColor: 'var(--info-light)' },
    { id: 11, type: 'offboarding', icon: '📦', titleAr: 'بدء إخلاء طرف', titleEn: 'Offboarding Started', descAr: 'تم بدء إجراءات إخلاء الطرف لـ محمد الشمري', descEn: 'Offboarding procedures started for Mohammed Al-Shammari', time: '2026-06-05T10:00:00', read: false, bgColor: 'var(--warning-light)' },
    { id: 12, type: 'missing-doc', icon: '📎', titleAr: 'مستندات ناقصة', titleEn: 'Missing Documents', descAr: 'عبدالله الدوسري - التأمين الطبي غير مرفق في الملف', descEn: 'Abdullah Al-Dosari - Medical insurance missing from file', time: '2026-06-04T09:00:00', read: false, bgColor: 'var(--danger-light)' }
  ],

  // ==========================================
  // ATTENDANCE RECORDS (sample)
  // ==========================================
  attendance: [
    { empId: '1001', date: '2026-06-08', checkIn: '07:55', checkOut: '17:05', status: 'present', hours: 9.17 },
    { empId: '1001', date: '2026-06-07', checkIn: '08:10', checkOut: '17:00', status: 'late', hours: 8.83 },
    { empId: '1001', date: '2026-06-05', checkIn: '07:50', checkOut: '17:00', status: 'present', hours: 9.17 },
    { empId: '1001', date: '2026-06-04', checkIn: '08:00', checkOut: '17:00', status: 'present', hours: 9 },
    { empId: '1001', date: '2026-06-03', checkIn: '08:00', checkOut: '16:30', status: 'early-departure', hours: 8.5 },
    { empId: '1010', date: '2026-06-08', checkIn: '13:30', checkOut: null, status: 'missing-checkout', hours: null },
    { empId: '1010', date: '2026-06-07', checkIn: '13:45', checkOut: '18:00', status: 'late', hours: 4.25 },
    { empId: '1010', date: '2026-06-05', checkIn: '14:00', checkOut: '18:10', status: 'late', hours: 4.17 },
    { empId: '1005', date: '2026-06-04', checkIn: null, checkOut: null, status: 'sick-leave', hours: 0 },
    { empId: '1005', date: '2026-06-03', checkIn: null, checkOut: null, status: 'sick-leave', hours: 0 },
    { empId: '1009', date: '2026-06-08', checkIn: null, checkOut: null, status: 'on-leave', hours: 0 }
  ],

  // ==========================================
  // SENSITIVE CHANGES LOG
  // ==========================================
  sensitiveChanges: [
    { empId: '1001', type: { ar: 'ترقية', en: 'Promotion' }, from: { ar: 'مطور أنظمة', en: 'Systems Developer' }, to: { ar: 'مطور أنظمة أول', en: 'Senior Systems Developer' }, date: '2025-06-01', approvedBy: { ar: 'سلطان القحطاني', en: 'Sultan Al-Qahtani' } },
    { empId: '1001', type: { ar: 'تعديل راتب', en: 'Salary Change' }, from: '15,000', to: '18,000', date: '2025-06-01', approvedBy: { ar: 'سلطان القحطاني', en: 'Sultan Al-Qahtani' } },
    { empId: '1002', type: { ar: 'نقل بين الأقسام', en: 'Department Transfer' }, from: { ar: 'قطاع التشغيل', en: 'Operations Sector' }, to: { ar: 'الموارد البشرية', en: 'Human Resources' }, date: '2024-01-15', approvedBy: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' } },
    { empId: '1005', type: { ar: 'تجديد عقد', en: 'Contract Renewal' }, from: '2024-03-31', to: '2026-03-31', date: '2024-03-15', approvedBy: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' } },
    { empId: '1002', type: { ar: 'تغيير حساب بنكي', en: 'Bank Account Change' }, from: 'SA98...1098', to: 'SA12...7777', date: '2026-05-12', approvedBy: { ar: 'نورة العتيبي', en: 'Noura Al-Otaibi' } }
  ],

  // ==========================================
  // OFFBOARDING CHECKLIST
  // ==========================================
  offboardingChecklist: [
    { id: 1, item: { ar: 'اللابتوب', en: 'Company Laptop' }, icon: '💻', responsible: { ar: 'تقنية المعلومات', en: 'IT' } },
    { id: 2, item: { ar: 'بطاقة الدخول', en: 'Access Card' }, icon: '🪪', responsible: { ar: 'الأمن', en: 'Security' } },
    { id: 3, item: { ar: 'بصمة الباب', en: 'Door Fingerprint Access' }, icon: '🚪', responsible: { ar: 'تقنية المعلومات', en: 'IT' } },
    { id: 4, item: { ar: 'المفاتيح', en: 'Keys' }, icon: '🔑', responsible: { ar: 'الشؤون الإدارية', en: 'Admin' } },
    { id: 5, item: { ar: 'حساب البريد الإلكتروني', en: 'Email Account' }, icon: '📧', responsible: { ar: 'تقنية المعلومات', en: 'IT' } },
    { id: 6, item: { ar: 'حسابات الأنظمة', en: 'System Accounts' }, icon: '🖥️', responsible: { ar: 'تقنية المعلومات', en: 'IT' } },
    { id: 7, item: { ar: 'صلاحيات السيرفر', en: 'Server Access' }, icon: '🖧', responsible: { ar: 'تقنية المعلومات', en: 'IT' } },
    { id: 8, item: { ar: 'صلاحيات NetSuite', en: 'NetSuite Access' }, icon: '☁️', responsible: { ar: 'تقنية المعلومات', en: 'IT' } },
    { id: 9, item: { ar: 'VPN', en: 'VPN Access' }, icon: '🔒', responsible: { ar: 'تقنية المعلومات', en: 'IT' } },
    { id: 10, item: { ar: 'التسوية المالية النهائية', en: 'Final Settlement' }, icon: '💰', responsible: { ar: 'المالية', en: 'Finance' } }
  ],

  // ==========================================
  // REQUEST TYPES CATALOG
  // ==========================================
  requestTypes: [
    { id: 'leave', icon: '🏖️', color: 'var(--success)', bgColor: 'var(--success-light)', nameAr: 'طلب إجازة', nameEn: 'Leave Request', initiatorAr: 'الموظف', initiatorEn: 'Employee', descAr: 'طلب إجازة سنوية، مرضية، زواج، وفاة، أمومة، أبوة', descEn: 'Annual, sick, marriage, bereavement, maternity, paternity leave' },
    { id: 'overtime', icon: '⏰', color: 'var(--accent-orange)', bgColor: 'var(--accent-orange-light)', nameAr: 'طلب عمل إضافي', nameEn: 'Overtime Request', initiatorAr: 'الموظف أو المدير المباشر', initiatorEn: 'Employee or Direct Manager', descAr: 'طلب ساعات عمل إضافية مع التعويض', descEn: 'Request extra work hours with compensation' },
    { id: 'attendance-correction', icon: '✋', color: 'var(--info)', bgColor: 'var(--info-light)', nameAr: 'تصحيح حضور', nameEn: 'Attendance Correction', initiatorAr: 'الموظف', initiatorEn: 'Employee', descAr: 'تصحيح تسجيل حضور أو انصراف مفقود', descEn: 'Fix missing check-in or check-out' },
    { id: 'remote-work', icon: '🏠', color: 'var(--purple)', bgColor: 'var(--purple-light)', nameAr: 'طلب عمل عن بعد', nameEn: 'Remote Work Request', initiatorAr: 'الموظف', initiatorEn: 'Employee', descAr: 'طلب العمل من خارج المقر', descEn: 'Request to work from outside office' },
    { id: 'salary-certificate', icon: '📜', color: 'var(--teal)', bgColor: 'var(--teal-light)', nameAr: 'شهادة راتب', nameEn: 'Salary Certificate', initiatorAr: 'الموظف', initiatorEn: 'Employee', descAr: 'طلب إصدار شهادة راتب رسمية', descEn: 'Request official salary certificate' },
    { id: 'bank-change', icon: '🏦', color: 'var(--info)', bgColor: 'var(--info-light)', nameAr: 'تغيير حساب بنكي', nameEn: 'Bank Account Change', initiatorAr: 'الموظف', initiatorEn: 'Employee', descAr: 'تغيير بيانات الحساب البنكي للراتب', descEn: 'Change salary bank account details' },
    { id: 'business-card', icon: '💼', color: 'var(--text-primary)', bgColor: 'var(--bg-tertiary)', nameAr: 'طلب بطاقة عمل', nameEn: 'Business Card Request', initiatorAr: 'المدير المباشر', initiatorEn: 'Direct Manager', descAr: 'طلب طباعة بطاقات عمل رسمية', descEn: 'Request official business cards printing' },
    { id: 'student-employee', icon: '🎓', color: 'var(--accent-orange)', bgColor: 'var(--accent-orange-light)', nameAr: 'إضافة متدرب / موظف طالب', nameEn: 'Add Student Employee', initiatorAr: 'القسم / القطاع', initiatorEn: 'Department / Sector', descAr: 'إضافة متدرب أو موظف طالب جديد', descEn: 'Add new trainee or student employee' },
    { id: 'bonus', icon: '🎁', color: 'var(--success)', bgColor: 'var(--success-light)', nameAr: 'مكافأة / حافز', nameEn: 'Bonus / Reward', initiatorAr: 'المدير المباشر', initiatorEn: 'Direct Manager', descAr: 'طلب صرف مكافأة أو حافز للموظف', descEn: 'Request one-time bonus or reward' },
    { id: 'resignation', icon: '🚪', color: 'var(--danger)', bgColor: 'var(--danger-light)', nameAr: 'استقالة / إنهاء خدمة', nameEn: 'Resignation / Termination', initiatorAr: 'الموظف أو المدير أو الموارد البشرية', initiatorEn: 'Employee, Manager, or HR', descAr: 'تقديم استقالة أو إنهاء خدمات', descEn: 'Submit resignation or terminate employment' },
    { id: 'clearance', icon: '📦', color: 'var(--warning)', bgColor: 'var(--warning-light)', nameAr: 'إخلاء طرف', nameEn: 'Clearance / Offboarding', initiatorAr: 'الموظف أو الموارد البشرية', initiatorEn: 'Employee or HR', descAr: 'إجراء إخلاء طرف كامل', descEn: 'Complete offboarding clearance' },
    { id: 'warning', icon: '⚠️', color: 'var(--danger)', bgColor: 'var(--danger-light)', nameAr: 'إنذار إداري', nameEn: 'Warning Notice', initiatorAr: 'المدير المباشر أو الموارد البشرية', initiatorEn: 'Direct Manager or HR', descAr: 'إصدار إنذار أو ملاحظة تأديبية', descEn: 'Issue warning or disciplinary notice' }
  ],

  // ==========================================
  // DASHBOARD STATS
  // ==========================================
  dashboardStats: {
    totalEmployees: 10,
    newAwaitingReview: 1,
    pendingApprovals: 4,
    onLeave: 1,
    expiringContracts: 2,
    missingDocuments: 4,
    attendanceIssues: 3,
    overtimePending: 0,
    warnings: 1,
    upcomingEvaluations: 10
  },

  // ==========================================
  // ROLES
  // ==========================================
  roles: [
    { id: 'employee', nameAr: 'موظف', nameEn: 'Employee', icon: '👤', color: 'var(--info)', bgColor: 'var(--info-light)', descAr: 'عرض الملف الشخصي، تقديم الطلبات، تتبع الحالة', descEn: 'View profile, submit requests, track status' },
    { id: 'manager', nameAr: 'مدير مباشر', nameEn: 'Direct Manager', icon: '👥', color: 'var(--success)', bgColor: 'var(--success-light)', descAr: 'عرض الفريق، الموافقات، تقييم الأداء', descEn: 'View team, approvals, performance evaluation' },
    { id: 'hr-specialist', nameAr: 'أخصائي موارد بشرية', nameEn: 'HR Specialist', icon: '📋', color: 'var(--purple)', bgColor: 'var(--purple-light)', descAr: 'مراجعة الطلبات، إدارة المستندات، إعداد الشهادات', descEn: 'Review requests, manage documents, prepare certificates' },
    { id: 'hr-manager', nameAr: 'مدير الموارد البشرية', nameEn: 'HR Manager', icon: '🏢', color: 'var(--accent-orange)', bgColor: 'var(--accent-orange-light)', descAr: 'الموافقة النهائية، التقارير، السياسات', descEn: 'Final approval, reports, policies' },
    { id: 'executive', nameAr: 'الرئيس التنفيذي', nameEn: 'Executive / President', icon: '🎯', color: 'var(--text-primary)', bgColor: 'var(--bg-tertiary)', descAr: 'الموافقات العليا، التقارير التنفيذية', descEn: 'High-level approvals, executive reports' },
    { id: 'it-officer', nameAr: 'مسؤول تقنية المعلومات', nameEn: 'IT Officer', icon: '💻', color: 'var(--teal)', bgColor: 'var(--teal-light)', descAr: 'معالجة طلبات البطاقات، إدارة الصلاحيات', descEn: 'Process card requests, manage access' }
  ]
};
})();
